api:
  name: "mulesoft-zip-template"
  version: "1.0.0"
  logger:
    package: "org.mulesoft.templates"
    
status:
  key: "JOB_STATUS"
  runnning: "RUNNING"
  complete: "COMPLETE"
  success: "SUCCESS"