#%RAML 1.0
title: zip-template
description: It show some examples of working with zip files.
baseUri: http://localhost:8081/

resourceTypes:
  healthCheck: !include fragments/health_check_pattern/main.raml 

uses:
  traits: library/traits.raml
#  resourceTypes: library/resourceTypes.raml 
  types: library/types.raml

/info:
  get:
    

/health:
  type: healthCheck

/mule-home:
  get:
    is: 
    - traits.query-params-path
    - traits.query-params-recursive
    #- traits.query-params-file-match
    displayName: List All Files in Mule Home
    description:
    
    responses:
      200:
        body:   
          application/json:
            type: types.mule-home
            
          application/xml:
           type: types.mule-home
          #application/yaml:

/zip:
  /compress:
    get:
      displayName: Compress using Mule Compression Module
      description: |
        
      is: [ traits.query-params-name ]
      responses: 
        200:
          body:
            application/json:

  /decompress: 
    get:
      displayName: Decompress using Mule Compression Module
      description:
      is: [ traits.query-params-zip ]
      responses: 
        200:
          body: 
            application/json:

  /archive:
    get:
      displayName: Archive using Mule Compression Module
      description: |
        ```java
        {
          "fileName": "fileContent"
        }
        ```
      is: [ traits.query-params-zip ]
      responses:
        200:
          body:
            application/json:

  /extract:
    get:
      displayName: Extract using Mule Compression Module
      is: [ traits.query-params-name ]
      responses:
        200:
          body:
            application/json:

  /zip:
    get:
      displayName: Archive a Zip file using Java Class
      is:
      - traits.query-params-zip:
      - traits.query-params-files
  
  /unzip:
    get:
      displayName: Extract a Zip file using Java Class
      is:
      - traits.query-params-zip
  
  /append:
    get:
      displayName: Include Files to existing Zip using Java Class
      is:
      - traits.query-params-zip
      - traits.query-params-files
  
  /entries:
    get:
      is:
      - traits.query-params-zip
      
      displayName: Get List of Entries inside Zip using Java Class (Without Extract)
      responses:
        200:
          body:
            application/json:
            

