#%RAML 1.0
title: zip-template
description: It show some examples of working with zip files.
baseUri: http://localhost:8081/

uses:
  traits: library/traits.raml
  #resourceTypes: 

types:
  mule-home: !include ./dataType/mule-home.raml

/mule-home:
  get:
    is: 
    - traits.query-params-path
    - traits.query-params-recursive
    displayName: List All Files in Mule Home
    description:
    
    #body:
      #{
      #  "createdSince": "2023-01-19T00:01:46.507-03:00",
      #  "createdUntil": "2023-01-19T00:01:46.508-03:00",
      #  "updatedSince": "2023-01-19T00:01:46.508-03:00",
      #  "updatedUntil": "2023-01-19T00:01:46.508-03:00",
      #  "accessedSince": "2023-01-19T00:01:46.508-03:00",
      #  "accessedUntil": "2023-01-19T00:01:46.509-03:00",
      #  "notUpdatedInTheLast": 0,
      #  "updatedInTheLast": 0,
      #  "timeUnit": "",
      #  "filenamePattern": "",
      #  "minSize": 0,
      #  "maxSize": 0
      #}
    
    responses:
      200:
        body:   
          application/json:
            type: mule-home
            
          application/xml:
           type: mule-home
          #application/yaml:

/zip:
  /compress:
    get:
      displayName: Compress using Mule Compression Module
      description: |
        
      responses: 
        200:
          body:
            application/json:

  /decompress: 
    get:
      displayName: Decompress using Mule Compression Module
      description:
      responses: 
        200:
          body: 
            application/json:

  /archive:
    get:
      displayName: Archive using Mule Compression Module
      description: |
        ```java
        {
          "fileName": "fileContent"
        }
        ```
      responses:
        200:
          body:
            application/json:

  /extract:
    get:
      displayName: Archive using Mule Compression Module
      responses:
        200:
          body:
            application/json:

  /zip:
    get:
      displayName: Zip using Java Class
  
  /unzip:
    get:
      displayName: Unzip using Java Class
  
  /append:
    get:
      displayName: Include Files to existing Zip using Java Class
  
  /entries:
    get:
      is:
      - traits.query-params-zip
      
      displayName: Get List of Entries inside Zip using Java Class (Without Extract)
      responses:
        200:
          body:
            application/json:
            

/healthcheck:
  displayName: Health Check API
  get:
    displayName: Healt Check API
    responses:
      200:
        body:
          application/json:
